version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    groups:
      clap:
        patterns:
          - "clap"
          - "clap_*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: /docs/vercel
    schedule:
      interval: monthly
