changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - feat
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Chores 🧹
      labels:
        - chore
        - refactor
        - doc
    - title: Dependencies ⬆️⬇️
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
