mod ascii_art;
pub mod cli;
pub mod cli_utils;
mod commit_info;
mod deps;
pub mod error;
mod image_backends;
pub mod info;
mod info_field;
mod language;
mod license;
pub mod printer;
pub mod repo;
mod serializer;
mod text_color;
mod utils;
