pub mod ascii_art;
pub mod cli;
pub mod cli_utils;
pub mod commit_info;
pub mod deps;
pub mod error;
pub mod image_backends;
pub mod info;
pub mod info_fields;
pub mod language;
pub mod license;
pub mod printer;
pub mod repo;
pub mod text_color;
mod utils;
