name: Bug report 🐛
description: Create a bug report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! ❤️
  - type: textarea
    attributes:
      label: Current behavior 😯
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior 🤔
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: Describe how we can reproduce this bug.
      placeholder: |
        1.
        2.
        3.
