name: Feature request ðŸ’„
description: Suggest an improvement
labels: ["âœ¨ enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! â¤ï¸
  - type: textarea
    attributes:
      label: Summary ðŸ’¡
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Motivation ðŸ”¦
      description: >
        What are you trying to accomplish?
        How has the lack of this feature affected you?
