name: Supported Languages Badge
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  make-badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Language Count
        uses: spenserblack/actions-set-output@v0.1
        id: lang-count
        with:
          variables: COUNT=$(cargo run -- --languages | wc -l)
      - name: Get Badge
        run: curl https://img.shields.io/badge/supported%20languages-${{ steps.lang-count.outputs.COUNT }}-blue > ./assets/supported-languages.svg
      - name: Commit Badge
        continue-on-error: true
        run: |
          git add ./assets
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update supported languages badge [Skip CI]"
          git push
