name: Web UI CI
on:
  push:
    branches: ["main"]
    paths:
      - "docs/vercel/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/vercel/**"

jobs:
  check:
    name: Check Vercel Code Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/vercel

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/vercel/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Svelte Check
        run: npm run check:svelte -- --fail-on-warnings

      - name: ESLint
        run: npm run check:lint

      - name: Prettier
        run: npm run check:prettier
